import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SmoothScroll from "./components/SmoothScroll";
import Footer from "./components/Footer";
import { ModalProvider } from "./context/ModalContext";
import ContactModal from "./components/modals/ContactModal";
import DetailModal from "./components/modals/DetailModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden bg-white text-slate-900 selection:bg-orange-500 selection:text-white relative">
        
        {/* Fixed Background Grid */}
        <div 
          className="fixed inset-0 z-[-1] pointer-events-none bg-white"
          style={{
            backgroundSize: "50px 50px",
            backgroundImage: "linear-gradient(to right, rgba(0, 0, 0, 0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(0, 0, 0, 0.08) 1px, transparent 1px)"
          }}
        />

        <ModalProvider>
          <SmoothScroll>
            <Navbar />
            {children}
            <Footer />
            <ContactModal />
            <DetailModal />
          </SmoothScroll>
        </ModalProvider>
      </body>
    </html>
  );
}
